OBJS += passes/guide/write_guide.o
OBJS += passes/guide/guide_connect.o
OBJS += passes/guide/guide_flatten.o
OBJS += passes/guide/guide_multi.o
OBJS += passes/guide/extract_multi.o
OBJS += passes/guide/guide_test.o